spec:
  inputs:
    single_tag_input:
      default: ""
      description: "SADECE 1 KEZ çalışacak Cucumber tag'ini girin (Örn: @Login veya @Setup). Boş bırakılabilir."
    loop_tag_input:
      default: ""
      description: "Arka arkaya 1000 KEZ döngüde çalışacak stres testi tag'ini girin (Örn: @SatisVeyaIptal). Boş bırakılabilir."

---

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  APPIUM_URL: "http://127.0.0.1:4723"
  SINGLE_TAG: "$[[ inputs.single_tag_input ]]"
  LOOP_TAG: "$[[ inputs.loop_tag_input ]]"

stages:
  - build
  - test

compile_project:
  stage: build
  script:
    - mvn clean compile

pos_automation_tests:
  stage: test
  tags:
    - pos-runner
  before_script:
    - echo "=== Appium Kontrol Ediliyor ==="
    # Bilgisayarda açık kalmış eski Appium (node) süreçlerini CMD üzerinden temizler
    - taskkill /F /IM node.exe /T || echo "Calisan Appium sureci bulunamadi."
    # Appium'u Windows arka planında sıfırdan başlatır
    - echo "🚀 Appium Server Arka Planda Baslatiliyor..."
    - start /B appium --log-level debug --log-no-colors > appium.log 2>&1
    # 5 saniye beklemek için Windows'un en kararlı ping komutunu kullanıyoruz
    - ping 127.0.0.1 -n 6 > nul
  script:
    - echo "Fiziksel POS Test Sureci Basliyor..."
    
    # EĞER SINGLE_TAG DOLUYSA: Sadece o tag'i çalıştırır
    - if not "%SINGLE_TAG%"=="" ( mvn test -Dappium.url=%APPIUM_URL% -Dcucumber.filter.tags="%SINGLE_TAG%" )


    # EĞER İKİ INPUT DA BOŞSA: Tüm testleri sırasıyla koşturur
    - if "%SINGLE_TAG%"=="" if "%LOOP_TAG%"=="" ( mvn test -Dappium.url=%APPIUM_URL% )

  after_script:
    # Test bittiğinde logları GitLab console ekranında görebilmek için:
    - echo "=== APPIUM LOGLARI ==="
    - type appium.log || echo "Log dosyasi henuz olusmadi."
  allow_failure: true
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
      - appium.log
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml